---
- name: Add GitLab package repository key
  ansible.builtin.apt_key:
    url: "{{ gitlab_repo_url }}"
    state: present

- name: Add GitLab package repository
  ansible.builtin.apt_repository:
    repo: "deb https://packages.gitlab.com/gitlab/gitlab-ce/ubuntu/ {{ ansible_distribution_release }} main"
    state: present
    filename: gitlab-ce
    update_cache: true

- name: Install GitLab CE packages
  ansible.builtin.apt:
    name: "{{ gitlab_packages }}"
    state: present
    update_cache: true

- name: Configure GitLab
  ansible.builtin.template:
    src: gitlab.rb.j2
    dest: /etc/gitlab/gitlab.rb
    owner: root
    group: root
    mode: "0644"
  notify: Reconfigure GitLab

- name: Run GitLab reconfigure
  ansible.builtin.command: gitlab-ctl reconfigure
  args:
    chdir: /
  register: gitlab_reconfigure_result
  changed_when: true