grafana:
  enabled: true

  persistence:
    enabled: true
    storageClassName: nfs
    size: 10Gi

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1
      memory: 1Gi


alertmanager:
  enabled: true

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi


prometheus:
  enabled: true

  prometheusSpec:

    retention: 30d

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: nfs
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 30Gi

    resources:
      requests:
        cpu: 200m
        memory: 256Mi
      limits:
        cpu: 1
        memory: 2Gi


kubeStateMetrics:
  enabled: true


nodeExporter:
  enabled: true


defaultRules:
  create: true