apiVersion: k8s.keycloak.org/v2beta1
kind: Keycloak
metadata:
  name: keycloak
  namespace: keycloak

spec:
  instances: 1

  db:
    vendor: postgres
    host: postgres.database.svc.cluster.local
    port: 5432
    database: keycloak

    usernameSecret:
      name: keycloak-db
      key: username

    passwordSecret:
      name: keycloak-db
      key: password

  http:
    httpEnabled: true

  hostname:
    hostname: https://keycloak.k8s.lab

  proxy:
    headers: xforwarded

  ingress:
    enabled: false